// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pharmacy_ASP_API.Models;

#nullable disable

namespace Pharmacy_ASP_API.Migrations
{
    [DbContext(typeof(PharmacyDbContext))]
    partial class PharmacyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FinanceReport", b =>
                {
                    b.Property<Guid>("ReportsReportId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FinancesReportId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FinancesOrderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FinancesPatientId")
                        .HasColumnType("char(36)");

                    b.HasKey("ReportsReportId", "FinancesReportId", "FinancesOrderId", "FinancesPatientId");

                    b.HasIndex("FinancesReportId", "FinancesOrderId", "FinancesPatientId");

                    b.ToTable("FinanceReport");
                });

            modelBuilder.Entity("MedicationKnowledgeOrder", b =>
                {
                    b.Property<Guid>("MedicationKnowledgesMedicationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OrdersOrderId")
                        .HasColumnType("char(36)");

                    b.HasKey("MedicationKnowledgesMedicationId", "OrdersOrderId");

                    b.HasIndex("OrdersOrderId");

                    b.ToTable("MedicationKnowledgeOrders", (string)null);
                });

            modelBuilder.Entity("Pharmacy_ASP_API.Models.Entities.Finance", b =>
                {
                    b.Property<Guid>("ReportId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ReportId", "OrderId", "PatientId");

                    b.HasIndex("PatientId");

                    b.ToTable("Finances");
                });

            modelBuilder.Entity("Pharmacy_ASP_API.Models.Entities.MedicationKnowledge", b =>
                {
                    b.Property<Guid>("MedicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ClinicalUse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Expirydate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("StockId")
                        .HasColumnType("char(36)");

                    b.HasKey("MedicationId");

                    b.HasIndex("StockId");

                    b.ToTable("MedicationKnowledges");
                });

            modelBuilder.Entity("Pharmacy_ASP_API.Models.Entities.MedicationRequest", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DoseInstruction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DrInBed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DrOutBed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StatusTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("authoredTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RequestId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("MedicationRequests");
                });

            modelBuilder.Entity("Pharmacy_ASP_API.Models.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MedicationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MedicationRequestId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StockId")
                        .HasColumnType("char(36)");

                    b.HasKey("OrderId");

                    b.HasIndex("MedicationId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ReportId");

                    b.HasIndex("StockId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Pharmacy_ASP_API.Models.Entities.Patient", b =>
                {
                    b.Property<Guid>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Pharmacy_ASP_API.Models.Entities.Report", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("OrderCount")
                        .HasColumnType("int");

                    b.Property<int>("StockAcidPrice")
                        .HasColumnType("int");

                    b.Property<int>("TotalSales")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Pharmacy_ASP_API.Models.Entities.Stock", b =>
                {
                    b.Property<Guid>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MedicationId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("WarningDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("StockId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("FinanceReport", b =>
                {
                    b.HasOne("Pharmacy_ASP_API.Models.Entities.Report", null)
                        .WithMany()
                        .HasForeignKey("ReportsReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pharmacy_ASP_API.Models.Entities.Finance", null)
                        .WithMany()
                        .HasForeignKey("FinancesReportId", "FinancesOrderId", "FinancesPatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicationKnowledgeOrder", b =>
                {
                    b.HasOne("Pharmacy_ASP_API.Models.Entities.MedicationKnowledge", null)
                        .WithMany()
                        .HasForeignKey("MedicationKnowledgesMedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pharmacy_ASP_API.Models.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pharmacy_ASP_API.Models.Entities.Finance", b =>
                {
                    b.HasOne("Pharmacy_ASP_API.Models.Entities.Patient", null)
                        .WithMany("Finances")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pharmacy_ASP_API.Models.Entities.MedicationKnowledge", b =>
                {
                    b.HasOne("Pharmacy_ASP_API.Models.Entities.Stock", "Stock")
                        .WithMany("MedicationKnowledges")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Pharmacy_ASP_API.Models.Entities.MedicationRequest", b =>
                {
                    b.HasOne("Pharmacy_ASP_API.Models.Entities.Order", null)
                        .WithOne("MedicationRequest")
                        .HasForeignKey("Pharmacy_ASP_API.Models.Entities.MedicationRequest", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pharmacy_ASP_API.Models.Entities.Order", b =>
                {
                    b.HasOne("Pharmacy_ASP_API.Models.Entities.MedicationKnowledge", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pharmacy_ASP_API.Models.Entities.Patient", "Patient")
                        .WithMany("Orders")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pharmacy_ASP_API.Models.Entities.Report", "Report")
                        .WithMany("Orders")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pharmacy_ASP_API.Models.Entities.Stock", "Stock")
                        .WithMany("Orders")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medication");

                    b.Navigation("Patient");

                    b.Navigation("Report");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Pharmacy_ASP_API.Models.Entities.Order", b =>
                {
                    b.Navigation("MedicationRequest")
                        .IsRequired();
                });

            modelBuilder.Entity("Pharmacy_ASP_API.Models.Entities.Patient", b =>
                {
                    b.Navigation("Finances");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Pharmacy_ASP_API.Models.Entities.Report", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Pharmacy_ASP_API.Models.Entities.Stock", b =>
                {
                    b.Navigation("MedicationKnowledges");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
